version: '2.4'
services:
  caddy:
      image: docker.io/caddy
      restart: always
      cap_add:
        - NET_ADMIN
      ports:
          - 80:80
          - 443:443
      volumes:
          - ./Caddyfile:/etc/caddy/Caddyfile
          - caddy_data:/data
          - caddy_config:/config

  jellyfin:
    image: jellyfin/jellyfin
    container_name: 'jellyfin'
    ports: 
      - 8096:8096
    volumes:
      - jellyfin-config:/config
      - jellyfin-cache:/cache
      # Update this configuration as desired
      - type: bind
        source: "/media/chestnut/My Passport/jellyfin"
        target: /media
    restart: always

volumes:
  caddy_config:
  caddy_data:
  jellyfin-config:
  jellyfin-cache: